{% set name = "mimerender" %}
{% set version = "0.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "e7f1377efee18c3f562cee54907a3329223c824332889fb74b745ddfd0a9b1c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - python-mimeparse >=0.1.4

test:
  imports:
    - mimerender

about:
  home: https://github.com/martinblech/mimerender
  license: MIT
  # license_file: No MANIFEST.in - see https://github.com/martinblech/mimerender/issues/34
  license_family: MIT
  summary: 'RESTful HTTP Content Negotiation for Flask, Bottle, web.py and webapp2 (Google App Engine)'
  dev_url: https://github.com/martinblech/mimerender
  doc_url: https://mimerender.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
