travis:
  secure:
    BINSTAR_TOKEN: OqgiZwtmwm3x7DWdIY7WQNkYz5h6UwlYAK5Eu6koRvgisSI/Y3jXkTGBCrpUa6lLzf5mDH1IdjQHsx9HzVmS62/ihpqr1SlNsAtbCIEgSMrjHm7+0PYz8c5FtV29hlyvFki0VHoz0z6AOMY6FwHwPi6Ol2YYNkdAESl7xgtgJqd11PNV8ER28mAGIgxmXZsGLBfiajkq35Fqb4DhPnFac437A62dUru+kI65+0a2AfulUaEUDnEZmkpIrQoT36d/gKQD9qiN2eC0rv/g/Jn/y/vnBvqXIsPlMv3RVh93Ok9hCyUL/vMCdgPPqWPSnbi2MVkKGFjKQK7yV5nE02BdLN6lXaE2MJv4fx8tl0yV8+1tNJ49gujFlDtNc+BRuZwaxoUX8zCNFlE8D69snp/fCI8W9EC7sw1P/srwp7Njz+PZxV5Pxqjx9es8BwqyuZ/nJg2bxUuPZ9/RhlgEsZNQ7VcQHJryCQ2jQJV1ams//FwNHtpsdis3V8j+EU8V5FrzgJ5Zuu5qVzKtVOT+yBWv2ot9wY/P7KejBICdGYGip+cQr/7f2ODBGqrbrwkrXhcrTUnKmZGkTiVnErzbEWFIQXJMLWDgaN9g8n+TEcS8KlR4pCPK7Y0eXg5ekYxm9a3Pbwobgu1LddP9amDnqGnf4If8G9FJv0nqYTp+ExmORq0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
