travis:
  secure:
    BINSTAR_TOKEN: b8rvQv9IxjGnZpCRPysY4knJHaRkgosoQg9DjduqMew9YgFGhOpzlOTi6mz3whIH9VjYwtlRZk91NVBd+h0mF+I+H1Ac2ycfqNrDCb/OjhHEVIt/oTGkpDIhHpigGQ6As6qFf1zQs9WoaWSrWWoE9Zqi7dGPsi5BJWwRS5iaIV8ZmT5GTnhbmWL2CjwsvW6iPcd+upkNom4mIll6+2SoWlBuzpCywlFTDNFNEHYytOGLH3tv7bHhw7kn44y/b0+KQhDzkE7HQBioxkLn2L+zD/OAa+sXcuLPcRzUhxtMGuJrhhT3yeGAyScYOMW6TirwiNTziN3/mzga7Ub6I+wNjQB4krn9HgoKsJVKFbYILzAbP2NFvHE3AWtQmQ77Cxumohud/7EJIzhscv991PchAFfWpu7mIExacYPbcEKzTCwkUOx4QVsZjYgE/2/rE1YX3ObjxoJy8wOyaWpwGF1bsrZtz7xRp7x1eDkzxbvgsjDVymBtBMyPNSNUjk73DiVwSd3OKe0CRWYfpxSOZJGYTHXF+8dhKzf3fyaz1il5LFcf5gaSG3q+inlNWJqfORP4frYBz2VFtMJhrmgiXjr8/xBNBgEJGEZZHwForumGM0t9gM9pTijmt6y6tY+iVKwXrG/6sN9ftgJmkKojBVxo6z/SxOITWdXE6VtkpkGNOFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
